### PR TITLE
Improve IDE completion

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by bakura10** [comment]
Hhhmm... I'm not sure the extra dependency is worthwhile considering the few benefits it brings. I really prefer to use $this->assert. I find it clearer and it is more convenient for people familiar with PhpUnit.

**Comment by weierophinney** [comment]
As I've mentioned in IRC previously, the trait is to be considered in the context of the class composing it, which means calling assertion methods directly on `$this` is perfectly valid and readable.

If your IDE is complaining about the file, add an exclusion for it.

**Comment by Maks3w** [comment]
My IDE offers autocompletetions and suggestion where before not. Scrutinizer-CI and other type checkers tools are fine with this.


This was already done on zend-inputfilter and there was not problems. I don't understand why reject this.


Both ways are valid but this offers a noticeable gain.

**Comment by bakura10** [comment]
What is the gain? I don't see any expect it makes it confusing because I don't know why this assert is here while it's as easy to type $this-> :)

**Pull request closed without merging**
