### PR TITLE
Updated to php-coveralls/php-coveralls

### PR DESCRIPTION
**Pull request by webimpress**
With version 2 package has been renamed from `satooshi/php-coveralls` to `php-coveralls/php-coveralls`, and the script has been renamed from `coveralls` to `php-coveralls`

### CODE REVIEW

**Comment by Ocramius** [comment]
@webimpress I'm merging this into `develop` only, since it is an improvement.

**Comment by Ocramius** [comment]
Merged via zendframework/zend-servicemanager@c7fd498d0b75f867256007057d31529a4543700e

**Comment by webimpress** [comment]
@Ocramius, this is not an improvement, this is a hotfix. The current version (on master) is not working properly.

**Comment by Ocramius** [comment]
@webimpress that only affects builds, not consumers, so I'd rather have a non-working `master` than backporting something that is only relevant to project development

**Comment by webimpress** [comment]
@Ocramius right, it affects builds, so in case of new "hotfix" to master, we can't see coverage. This is why I think it should be merged to master straight away as a hotfix.

**Pull request closed without merging**
