### PR TITLE
Added a benchmark for `ServiceManager#has()`

### PR DESCRIPTION
**Pull request by fhein**
This PR just adds a benchmark for ServiceManager::has().

### CODE REVIEW

**Comment by Ocramius** [comment]
@fhein changed base - please rebase the branch when you got a chance

**Comment by fhein** [comment]
Closed in favour of #220.

**Comment by fhein** [comment]
Closed in favour of #220.

**Comment by Ocramius** [comment]
Manually merging this into `develop`

**Comment by Ocramius** [comment]
Manually merged into `develop` via zendframework/zend-servicemanager@59d699bea6af4872e7019275afd2679ca85fb45b

**Pull request closed without merging**
