### PR TITLE
Add setAliases and setFactories methods branch 2.7

### PR DESCRIPTION
**Pull request by malinink**
We should add methods to  branch 2.7 in order to change other components that to use them before we migrate to SM3.

More information could be found here #112

All components listed in symmetric PR #114

### CODE REVIEW

**Comment by Ocramius** [comment]
Disagree with this approach. This API should at least be private and used only by internal `zendframework/zend-servicemanager` components. `public` is a no-go in my opinion, especially after all the effort put into reducing the surface of interaction with the ServiceManager

**Comment by malinink** [comment]
@Ocramius 
If that methods will be protected or private then we could not use them outside class.
Both of methods made for the same as a function setFactory and setAlias (and that method are public).

The reason of creation new methods is new SM3, where it is better to add all aliases or factories at once due to performance issues.

Maybe there are any other ways to do that? (all discussion is here #112 and here #122)

**Comment by Ocramius** [comment]
> The reason of creation new methods is new SM3, where it is better to add all aliases or factories at once due to performance issues.

I understand that. I wonder if we have a way to avoid that, and instead merge configs upfront (which would remove an entire set of problems in this space completely)

**Comment by weierophinney** [comment]
Use configure() is you want to do multiple aliases or factories at once.
It's not BC, bit works for v3.

**Comment by malinink** [comment]
@Ocramius @weierophinney 
As I see, these PR already exist in all depend components. 
 - https://github.com/zendframework/zend-form/pull/77
 - https://github.com/zendframework/zend-i18n/pull/47

So it is better to close both my PR (#114 #115), and issue (#112).

**Comment by Ocramius** [comment]
Closing as per discussion

Moving on to:

 * zendframework/zend-form#77
 * zendframework/zend-i18n#47

**Pull request closed without merging**
