### PR TITLE
Added PHP 7.3 support

### PR DESCRIPTION
**Pull request by michalbundyra**
Updated Travis CI configuration to run all tests on PHP 7.3 with lowest/locked/latest dependencies

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
The build is still failing here

**Comment by webimpress** [comment]
@Ocramius, updated now. Not sure about the milestone 3.4.0 as develop now is 4.0:

```
 "dev-develop": "4.0-dev"
```

Maybe I should change the target of that PR?

**Comment by Ocramius** [comment]
@webimpress I was working on 4.0 on `develop`, but it will likely happen in +1 year anyway, since PHP 7.4 will have the interesting stuff, while 7.3 is kinda dull :)

**Comment by webimpress** [comment]
@Xerkus I forgot about this PR and just created new to `master`: #277

**Comment by Xerkus** [comment]
I think suggested `ocramius/proxy-manager` should be bumped to `^2.2.0`, along with dev dependency, and conflict changed to specific version of `"zendframework/zend-code": "3.3.0"` to reduce unintended impact

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas/laminas-servicemanager; a new issue has been opened at https://github.com/laminas/laminas-servicemanager/issues/6.

**Comment by weierophinney** [comment]
This repository has been moved to laminas/laminas-servicemanager. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-servicemanager to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-servicemanager.
 - In your clone of laminas/laminas-servicemanager, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

**Pull request closed without merging**
