### PR TITLE
Bugfix/invokable factory options affect multiple instantiations

### PR DESCRIPTION
**Pull request by AndrolGenhald**
Fix issue #126 
I don't really like checking instanceof InvokableFactory, but at least it works.

### CODE REVIEW

**Comment by AndrolGenhald** [comment]
Any word on this? It's still an issue.

**Comment by weierophinney** [comment]
Thanks, @AndrolGenhald\! Released with 2.7.7

**Comment by thestanislav** [comment]
It seem this breaks default initialization of Zend\Filter\Boolean
First parameter of constructor must be null, not an empty array for default initialization 
https://github.com/zendframework/zend-filter/blob/master/src/Boolean.php#L62

**Comment by adamlundrigan** [comment]
@weierophinney ping (BC break)

**Pull request merged**
